modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/AmbientSounds/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="ambientsounds"
    logoFile="ambientsounds.png"
    version="6.1.3"
    displayName="AmbientSounds"
    displayURL="https://modrinth.com/mod/ambientsounds"
    authors="CreativeMD"
    description='''Expands minecraft's ambient sounds.'''
    displayTest="NONE"

[[dependencies.ambientsounds]]
    modId="neoforge"
    type="required"
    versionRange="[21.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.16,)"

[[mixins]]
   config="ambientsounds.mixins.json"

